Intel Xeon W-2133
10
titanxp
Thu Dec  6 19:30:18 CET 2018
a1b7a9b00a374ba55f9391170e6d38d4be847d88
make: 'cluster_mpib' is up to date.
node titanxp, task   0 of   1 tasks, thread   0 of   6 threads, on cpu   0
node titanxp, task   0 of   1 tasks, thread   1 of   6 threads, on cpu   1
node titanxp, task   0 of   1 tasks, thread   2 of   6 threads, on cpu   2
node titanxp, task   0 of   1 tasks, thread   3 of   6 threads, on cpu   3
node titanxp, task   0 of   1 tasks, thread   4 of   6 threads, on cpu   4
node titanxp, task   0 of   1 tasks, thread   5 of   6 threads, on cpu   5
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node titanxp exited on signal 9 (Killed).
--------------------------------------------------------------------------
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node titanxp exited on signal 9 (Killed).
--------------------------------------------------------------------------
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node titanxp exited on signal 9 (Killed).
--------------------------------------------------------------------------
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node titanxp exited on signal 9 (Killed).
--------------------------------------------------------------------------
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node titanxp exited on signal 9 (Killed).
--------------------------------------------------------------------------
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Caught std::exception: std::bad_alloc
Fri Dec  7 04:36:39 CET 2018
